### ISSUE TITLE
siamese_mask_rcnn.py

### ISSUE THREAD

**Issue by andrew-jeremy** [phj128/siamese-mask-rcnn_mmdetection#1]
This is not a repo. It is a joke ! You point to someone else's repo and then provide code that does not exist. Where is siamese_mask_rcnn.py ?

**Comment by phj128** [comment]
We directly change the code in mmdet/models/detectors/two_stages.py and mmdet/datasets/coco.py to achieve siamese mask rcnn. You can check the code first.
