### ISSUE TITLE
training siamese_mask_rcnn got TypeError

### ISSUE THREAD

**Issue by edwardpwtsoi** [phj128/siamese-mask-rcnn_mmdetection#2]
Hi,

I tried to reproduce your work following the readme.md

when i ran 

```console
python tools/train.py configs/siamese_mask_rcnn.py
```
I got warning and error as following:
```console
2019-11-26 10:42:32,468 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
  File "tools/train.py", line 106, in <module>
    main()
  File "tools/train.py", line 86, in main
    train_dataset = build_dataset(cfg.data.train)
  File "/workspace/src/mmdetection/mmdet/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/workspace/src/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'img_scale'
```

I suspected that is a error from mmcv but i could not found any open or closed issue mentioned about that.
I am planning to modify your code such as remove img_scale argument
Could you advise would that be appropriate to do so?

**Environment**
i am using nvidia-docker container of pytorch
nvcr.io/nvidia/pytorch:19.09-py3

**Comment by mi804** [comment]
I guess you run `python setup.py develop`  in folder mmdetection/ and thus installed a wrong version of mmdetection.
you may run 
`python setup.py develop` 
in the folder :  siamese-mask-rcnn_mmdetection/ instead of mmdetection/.
