### ISSUE TITLE
Would you provide a trained model?

### ISSUE THREAD

**Issue by rickygao** [phj128/siamese-mask-rcnn_mmdetection#3]
Very kind of you!

**Comment by phj128** [comment]
I am sorry that I cannot provide the model now due to COVID-19. The model is on my computer which is shut down in my dorm now, however, I cannot return my school to upload it.

**Comment by rickygao** [comment]
> I am sorry that I cannot provide the model now due to COVID-19. The model is on my computer which is shut down in my dorm now, however, I cannot return my school to upload it.

uhhh, however, thanks.
